server:
  port: 8282
spring:
  security:
    user:
      name: anuradha
      password: anuradha123
      roles: ADMIN,USER
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: mobile
          client-secret: pin
          introspection-uri: 3600
          authorized-grant-types: refresh_token, authorization_code, password, client_credentials
#                scope: READ, WRITE
#              authorization:
#                check-token-access: permitAll